#
# Deithwen Addan yn Carn aep Morvudd
#


#


#


#
class ElementFlow:
    """
    A structure representing flows generated by element of financial essence.
    Implements data treatments, timestamps controls, 3-view flow representations on its level of detalization.

    Inheritor naming convention: EF_<here 5 literal code>_<here 2 literal version>
    """
    def __init__(self, **kwargs):
        """
        To be implemented
        """
        pass

    def source(self, **kwargs):
        """
        Loads all series needed for calculations. Follows conventions defined under __init__

        To be implemented
        """

    def ds(self, **kwargs):
        """
        Calculates "per share" flow (differential)

        To be implemented
        """
        return

    def dq(self, **kwargs):
        """
        Calculates "per quantity" flow (differential)

        To be implemented
        """
        return

    def dc(self, **kwargs):
        """
        Calculates "per capital" flow (cumulative)

        To be implemented
        """
        return


class Closer:
    """
    Inheritor naming convention: CS_<here 5 literal code>_<here 2 literal version>
    """
    def __init__(self, **kwargs):
        """
        To be implemented
        """
        pass

    def resolve(self, flow):
        """
        Finds trade resolution for given flow

        To be implemented
        """
        pass


class Essence:
    """
    Inheritor naming convention: ES_<here 5 literal code>_<here 2 literal version>
    """
    def __init__(self, flow, closer):
        self.flow = flow
        self.closer = closer

    def long_flow(self, start, end):
        self.flow.dq(start=start, end=end, pos_one_long=True)
        return self.flow

    def short_flow(self, start, end):
        self.flow.dq(start=start, end=end, pos_one_long=False)
        return self.flow

    def long_result(self, start, end):
        self.long_flow(start=start, end=end)
        return self.closer.resolve(self.flow)

    def short_result(self, start, end):
        self.short_flow(start=start, end=end)
        return self.closer.resolve(self.flow)


class Store:
    def __init__(self, essences):
        self.essences = essences
    # def __getattr__(self, item):
    #     ...

    def __getitem__(self, item):
        return self.essences[item]
